remote_theme: "coderua/infotorg-api-jekyll-theme@main"
# --- Jekyll configuration ---
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      show_navigation: true
sass:
  style: compressed # possible values: nested expanded compact compressed
plugins:
  # See the documentation for Jekyll SEO Tag: https://github.com/jekyll/jekyll-seo-tag
  - jekyll-seo-tag

subtitle: Test
